# WEB SCRAPING-ASSIGNMENT - 4

## Exercise 1 :

In [1]:
#Lets import all the necessary libraries 

import selenium                                     #library that is used to work with Selenium
from selenium import webdriver                      # importing webdriver module from selenium to open automated chrome window
import pandas as pd                                 # To create a Database
from selenium.webdriver.common.by import By         # importing inbuilt class By
import warnings
warnings.filterwarnings('ignore')                   # to ignore any sort of warning
import time                                         #used to stop search engine for a few secods

#Importing required Exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException , NoSuchElementException

#importing regax
import re

In [35]:
driver = webdriver.Chrome('chromedriver.exe') # Lets connect to the web driver

In [58]:
#Opening up wikipedia.com website on automated chrome window

url = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)

In [59]:
#Pulling the data from the table for the most viewed videos 

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC # expected_conditions module contains a set of predefined conditions to use with WebDriverWait used for the visibility_of_element_located to be able to get the elements in the table as shown on website list  
import pandas as pd
import html5lib
import lxml
from bs4 import BeautifulSoup


data = WebDriverWait(driver, 20).until(EC.visibility_of_element_located((By.XPATH, "/html/body/div[3]/div[3]/div[5]/div[1]/table[2]"))).get_attribute("outerHTML")
df = pd.read_html(data)
df[0]
# So finally we see that by using the dataframe from pandas we read the data from html as it is storing the table data as list data and display as dataframe

,No.,Video name,Uploader,Views (billions),Publication date,Note,Unnamed: 6
0,1.,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,11.83,"June 17, 2016",[A],NaN
1,2.,"""Despacito""[7]",Luis Fonsi,8.02,"January 12, 2017",[B],NaN
2,3.,"""Johny Johny Yes Papa""[14]",LooLoo Kids,6.54,"October 8, 2016",[C],NaN
3,4.,"""Shape of You""[15]",Ed Sheeran,5.86,"January 30, 2017",[D],NaN
4,5.,"""Bath Song""[17]",Cocomelon – Nursery Rhymes,5.81,"May 2, 2018",[E],NaN
5,6.,"""See You Again""[18]",Wiz Khalifa,5.71,"April 6, 2015",[F],NaN
6,7.,"""Phonics Song with Two Words""[23]",ChuChu TV,5.04,"March 6, 2014",[G],NaN
7,8.,"""Uptown Funk""[24]",Mark Ronson,4.77,"November 19, 2014",[H],NaN
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[25]",Miroshka TV,4.74,"February 27, 2018",[I],NaN
9,10.,"""Wheels on the Bus""[26]",Cocomelon – Nursery Rhymes,4.69,"May 24, 2018",NaN,NaN
10,11.,"""Gangnam Style""[27]",Psy,4.62,"July 15, 2012",[J],NaN
11,12.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,4.52,"January 31, 2012",[K],NaN
12,13.,"""Dame Tu Cosita""[33]",El Chombo,4.15,"April 5, 2018",NaN,NaN
13,14.,"""Sugar""[34]",Maroon 5,3.79,"January 14, 2015",NaN,NaN
14,15.,"""Roar""[35]",Katy Perry,3.69,"September 5, 2013",NaN,NaN
15,16.,"""Counting Stars""[36]",OneRepublic,3.69,"May 31, 2013",NaN,NaN
16,17.,"""Axel F""[37]",Crazy Frog,3.63,"June 16, 2009",NaN,NaN
17,18.,"""Sorry""[38]",Justin Bieber,3.61,"October 22, 2015",NaN,NaN
18,19.,"""Thinking Out Loud""[39]",Ed Sheeran,3.52,"October 7, 2014",NaN,NaN
19,20.,"""Baa Baa Black Sheep""[40]",Cocomelon – Nursery Rhymes,3.44,"June 25, 2018",NaN,NaN
20,21.,"""Dark Horse""[41]",Katy Perry,3.40,"February 20, 2014",NaN,NaN
21,22.,"""Faded""[42]",Alan Walker,3.38,"December 3, 2015",NaN,NaN
22,23.,"""Girls Like You""[43]",Maroon 5,3.35,"May 31, 2018",NaN,NaN
23,24.,"""Let Her Go""[44]",Passenger,3.35,"July 25, 2012",NaN,NaN
24,25.,"""Waka Waka (This Time for Africa)""[45]",Shakira,3.34,"June 4, 2010",NaN,NaN
25,26.,"""Perfect""[46]",Ed Sheeran,3.31,"November 9, 2017",NaN,NaN
26,27.,"""Bailando""[47]",Enrique Iglesias,3.30,"April 11, 2014",NaN,NaN
27,28.,"""Lean On""[48]",Major Lazer,3.29,"March 22, 2015",NaN,NaN
28,29.,"""Humpty the train on a fruits ride""[49]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,3.24,"January 26, 2018",NaN,NaN
29,30.,"""Shake It Off""[50]",Taylor Swift,3.23,"August 18, 2014",NaN,NaN
30,"As of December 8, 2022","As of December 8, 2022","As of December 8, 2022","As of December 8, 2022","As of December 8, 2022","As of December 8, 2022","As of December 8, 2022"

# Exercise 2 :

In [3]:
#Opening up bcci.tvwebsite on automated chrome window

url = 'https://www.bcci.tv/'
driver.get(url)

In [4]:
#clicking using absolute xpath function to click the International button on the menu to get to fixtures page

search_btn =  driver.find_element(By.XPATH,"/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a")
search_btn.click()

In [20]:
#Lets extract all the elements having match details date as well as time of match and time zone

Series = []
title_tags = driver.find_elements(By.XPATH,"//div[@class='fixture-card-top']")
for i in title_tags:
    Series.append(i.text.split('\n'))
print(Series)

[['INDIA A IN BANGLADESH MULTI DAY SERIES', '6 DEC 2022', 'LIVE'], ['AUSTRALIA WOMEN TOUR OF INDIA 2022', '9 DEC 2022', '7:00 PM IST'], ['INDIA TOUR OF BANGLADESH ODI SERIES 2022-23', '10 DEC 2022', '11:30 AM IST'], ['AUSTRALIA WOMEN TOUR OF INDIA 2022', '11 DEC 2022', '7:00 PM IST'], ['INDIA TOUR OF BANGLADESH TEST SERIES 2022-23', '14 DEC 2022', '9:30 AM IST'], ['AUSTRALIA WOMEN TOUR OF INDIA 2022', '14 DEC 2022', '7:00 PM IST'], ['AUSTRALIA WOMEN TOUR OF INDIA 2022', '17 DEC 2022', '7:00 PM IST'], ['AUSTRALIA WOMEN TOUR OF INDIA 2022', '20 DEC 2022', '7:00 PM IST'], ['INDIA TOUR OF BANGLADESH TEST SERIES 2022-23', '22 DEC 2022', '9:30 AM IST'], ['SRI LANKA TOUR OF INDIA T20 SERIES 2022-23', '3 JAN 2023', '7:30 PM IST'], ['SRI LANKA TOUR OF INDIA T20 SERIES 2022-23', '5 JAN 2023', '7:30 PM IST'], ['SRI LANKA TOUR OF INDIA T20 SERIES 2022-23', '7 JAN 2023', '7:30 PM IST'], ['SRI LANKA TOUR OF INDIA ODI SERIES 2022-23', '10 JAN 2023', '1:30 PM IST'], ['SRI LANKA TOUR OF INDIA ODI SERIES 2022-23', '12 JAN 2023', '1:30 PM IST'], ['SRI LANKA TOUR OF INDIA ODI SERIES 2022-23', '15 JAN 2023', '1:30 PM IST'], ['NEW ZEALAND TOUR OF INDIA ODI SERIES 2022-23', '18 JAN 2023', '1:30 PM IST'], ['NEW ZEALAND TOUR OF INDIA ODI SERIES 2022-23', '21 JAN 2023', '1:30 PM IST'], ['NEW ZEALAND TOUR OF INDIA ODI SERIES 2022-23', '24 JAN 2023', '1:30 PM IST'], ['NEW ZEALAND TOUR OF INDIA T20 SERIES 2022-23', '27 JAN 2023', '7:30 PM IST'], ['NEW ZEALAND TOUR OF INDIA T20 SERIES 2022-23', '29 JAN 2023', '7:30 PM IST'], ['NEW ZEALAND TOUR OF INDIA T20 SERIES 2022-23', '1 FEB 2023', '7:30 PM IST'], ['AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23', '9 FEB 2023', '9:30 AM IST'], ['AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23', '17 FEB 2023', '9:30 AM IST'], ['AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23', '1 MAR 2023', '9:30 AM IST'], ['AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23', '9 MAR 2023', '9:30 AM IST'], ['AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23', '17 MAR 2023', '1:30 PM IST'], ['AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23', '19 MAR 2023', '1:30 PM IST'], ['AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23', '22 MAR 2023', '1:30 PM IST']]

In [21]:
#To scrap data from the page for match title and place  

Match_Title  = []
Place = []




a1 = driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
a3 = driver.find_elements(By.XPATH,'//div[@class="fix-place ng-binding ng-scope"]')


try:
    
    for i in a1:
        Match_Title.append(i.text)
    for i in a3:
        Place.append(i.text)
except NoSuchElementException : 
    Match_Title.append('-')
    Place.append('-')

In [22]:
Match_Title

['First-Class Match -',
 '1st T20I -',
 '3rd ODI -',
 '2nd T20I -',
 '1st Test -',
 '3rd T20I -',
 '4th T20I -',
 '5th T20I -',
 '2nd Test -',
 '1st T20I -',
 '2nd T20I -',
 '3rd T20I -',
 '1st ODI -',
 '2nd ODI -',
 '3rd ODI -',
 '1st ODI -',
 '2nd ODI -',
 '3rd ODI -',
 '1st T20I -',
 '2nd T20I -',
 '3rd T20I -',
 '1st Test -',
 '2nd Test -',
 '3rd Test -',
 '4th Test -',
 '1st ODI -',
 '2nd ODI -',
 '3rd ODI -']

In [30]:
Place

['First-Class Match - Sylhet International Cricket Stadium, Sylhet',
 '1st T20I - DY Patil Stadium, NAVI MUMBAI',
 '3rd ODI - Zahur Ahmed Chowdhury Stadium, Chattogram',
 '2nd T20I - DY Patil Stadium, NAVI MUMBAI',
 '1st Test - Zahur Ahmed Chowdhury Stadium, Chattogram',
 '3rd T20I - Brabourne - CCI, Mumbai',
 '4th T20I - Brabourne - CCI, Mumbai',
 '5th T20I - Brabourne - CCI, Mumbai',
 '2nd Test - Shere Bangla National Stadium, Mirpur, Dhaka',
 '1st T20I - Mumbai',
 '2nd T20I - Pune',
 '3rd T20I - Rajkot',
 '1st ODI - Guwahati',
 '2nd ODI - Kolkata',
 '3rd ODI - Thiruvananthapuram',
 '1st ODI - Hyderabad',
 '2nd ODI - Raipur',
 '3rd ODI - Indore',
 '1st T20I - Ranchi',
 '2nd T20I - Lucknow',
 '3rd T20I - Ahmedabad',
 '1st Test - Nagpur',
 '2nd Test - Delhi',
 '3rd Test - Dharamsala',
 '4th Test - Ahmedabad',
 '1st ODI - Mumbai',
 '2nd ODI - Visakhapatnam',
 '3rd ODI - Chennai']

# Exercise 3:

In [31]:
#Opening up guru99.com website on automated chrome window

url = 'https://www.guru99.com/'
driver.get(url)

In [32]:
#clicking using absolute xpath function to click the Selenium button on homepage

search_btn =  driver.find_element(By.XPATH,"/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[2]/span[8]/a/img")
search_btn.click()

In [33]:
#clicking using absolute xpath function to click the Exception handling tutorial button button on selenium page

search_btn =  driver.find_element(By.XPATH,"/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a")
search_btn.click()

In [48]:
#Lets extract all the elements having title and description of selenium exception handling page

Data = []
title_tags = driver.find_elements(By.XPATH,"//div[@class='entry-content single-content']")
for i in title_tags:
    Data.append(i.text.split('\n'))
print(Data)

[['What is an Exceptions?', 'An exception is an error that happens at the time of execution of a program. However, while running a program, programming languages generates an exception that should be handled to avoid your program to crash.', 'The exception indicates that, although the event can occur, this type of event happens infrequently. When the method is not able to handle the Exception, it is thrown to its caller function.', 'In this Selenium tutorial, you will learn:', 'Types of Exceptions in Selenium Webdriver', '1. ElementNotVisibleException: This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.', '2. ElementNotSelectableException: This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact.', '3. NoSuchElementException: This Exception occurs if an element could not be found.', '4. NoSuchFrameException: This Exception occurs if the frame target to be switched to does not exist.', '5. NoAlertPresentException: This Exception occurs when you switch to no presented alert.', '6. NoSuchWindowException: This Exception occurs if the window target to be switch does not exist.', '7. StaleElementReferenceException: This Selenium exception occurs happens when the web element is detached from the current DOM.', '8. SessionNotFoundException: The WebDriver is acting after you quit the browser.', '9. TimeoutException: Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn’t found in the specified time.', '10. WebDriverException: This Exception takes place when the WebDriver is acting right after you close the browser.', '11. ConnectionClosedException: This type of Exception takes place when there is a disconnection in the driver.', '12. ElementClickInterceptedException: The command may not be completed as the element receiving the events is concealing the element which was requested clicked.', '13. ElementNotInteractableException: This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element.', '14. ErrorInResponseException: This happens while interacting with the Firefox extension or the remote driver server.', '15. ErrorHandler.UnknownServerException: Exception is used as a placeholder in case if the server returns an error without a stack trace.', '16. ImeActivationFailedException: This expectation will occur when IME engine activation has failed.', '17. ImeNotAvailableException: It takes place when IME support is unavailable.', '18. InsecureCertificateException: Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.', '19. InvalidArgumentException: It occurs when an argument does not belong to the expected type.', '20. InvalidCookieDomainException: This happens when you try to add a cookie under a different domain instead of current URL.', '21. InvalidCoordinatesException: This type of Exception matches an interacting operation that is not valid.', '22. InvalidElementStateException: It occurs when command can’t be finished when the element is invalid.', '23. InvalidSessionIdException: This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.', '24. InvalidSwitchToTargetException: This occurs when the frame or window target to be switched does not exist.', '25. JavascriptException: This issue occurs while executing JavaScript given by the user.', '26. JsonException: It occurs when you afford to get the session when the session is not created.', '27. NoSuchAttributeException: This kind of Exception occurs when the attribute of an element could not be found.', '28. MoveTargetOutOfBoundsException: It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document.', '29. NoSuchContextException: ContextAware does mobile device testing.', '30. NoSuchCookieException: This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.', '31. NotFoundException: This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.', '32. RemoteDriverServerException: This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.', '33. ScreenshotException: It is not possible to capture a screen.', '34. SessionNotCreatedException: It happens when a new session could not be successfully created.', '35. UnableToSetCookieException: This occurs if a driver is unable to set a cookie.', '36. UnexpectedTagNameException: Happens if a support class did not get a web element as expected.', '37. UnhandledAlertException: This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation.', '38. UnexpectedAlertPresentException: It occurs when there is the appearance of an unexpected alert.', '39. UnknownMethodException: This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.', '40. UnreachableBrowserException: This Exception occurs only when the browser is not able to be opened or crashed because of some reason.', '41. UnsupportedCommandException: This occurs when remote WebDriver doesn’t send valid commands as expected.', 'How to Handling Exceptions in Selenium', 'Here, are some important standard using which you can handle Exceptions in Selenium WebDriver:', 'Step 1) Try-catch', 'This method can catch Exceptions, which uses a combination of the try and catch keywords. Try command indicates the start of the block, and Catch is placed at the end of the try block, which helps to resolve the Exception.', 'try', '{', '// Code', '} catch (Exception e) {', '// Code for Handling exception', '}', 'Step 2) Multiple catch blocks', 'There are various types of Exceptions, and you can expect more than one exception from a single block of code. Multiple catches help you to handle every type of Exception separately with a separate block of code. It can be used for more than two catch blocks, and there is no limitation on the number of catch blocks.', 'try', '{', '//Code', '} catch (ExceptionType1 e1) {', '//Code for Handling Exception 1', '} catch (ExceptionType2 e2) {', '//Code for Handling Exception 2', '}', 'Step 3) Throw', 'When you want to generate an Exception, the Throw keyword is used to throw Exception to handle it in the run time. When you are throwing an Exception without handling it, then they need to use Throw keyword.', 'public static void anyFunction() throws Exception{', '', 'try {', '// write your code here', '} Catch (Exception b) {', '// Do whatever you want to perform ', '// Throw the Exception back to the system', 'throw(b);', '}', '}', 'Step 4) Multiple Exceptions', 'You can mention various Exceptions in the throws clause.', 'public static void anyFunction() throws ExceptionType1, ExceptionType2{', '', 'try {', '// write your code here', '} catch (ExceptionType1 e1) {', '// Code to handle exception 1', '} catch (ExceptionType1 e2) {', '// Code to handle exception 2', '}', 'Step 5) Finally', 'The Final keyword is used to create a block of code under the try block. It is the final code that helps you to executes irrespective of the occurrence of an exception', 'try {', '//Code', '} catch (ExceptionType1 e1) {', '//Catch block', '} catch (ExceptionType2 e2) {', '//Catch block', '} catch (ExceptionType3 e3) {', '//Catch block', '} finally {', '//The finally block always executes.', '}', 'Methods for displaying Exception', 'You can also use the following methods to display Exception Information:', 'printStackTrace(): This function prints stack trace, name of the Exception, and other useful description.', 'toString(): This function returns a text message describing the exception name and description.', 'getMessage(): Helps to displays the description of the Exception.', 'Summary:', 'An exception is an error that happens at the time of execution of a program.', 'Try-catch: This method can catch Exceptions, which uses a combination of the try and catch keywords.', 'Multiple catches help you to handle every type of Exception separately with a separate block of code.', 'Throw keyword is used to throw Exception to handle it in the run time.', 'printStackTrace(): This function prints stack trace, name of the Exception, and other useful description', 'toString(): This function returns a text message describing the exception name and description.', 'getMessage(): Helps to displays the description of the Exception.', 'You Might Like:', 'How to Read/Write Data from Excel File: Selenium POI', 'Using SoapUI with Selenium for Web Service Testing', 'Top 100 Selenium Interview Questions and Answers for 2022', 'How to Verify Tooltip using Selenium WebDriver', '19 Selenium Alternatives & Competitors (2022 Update)']]

# Exercise 4:

In [49]:
#Opening up statisticstimes.com website on automated chrome window

url = 'http://statisticstimes.com/'
driver.get(url)

In [53]:
#clicking using absolute xpath function to click the Economy button on homepage and select India from the dropdown menu
time.sleep(3)
search_btn =  driver.find_element(By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]")
search_btn.click()

search_btn1 =  driver.find_element(By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")
search_btn1.click()

In [54]:
#Clicking on GDP according to the Indian states

search_btn1 =  driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
search_btn1.click()

In [57]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC # expected_conditions module contains a set of predefined conditions to use with WebDriverWait used for the visibility_of_element_located to be able to get the elements in the table as shown on website list  
import pandas as pd
import html5lib
import lxml
from bs4 import BeautifulSoup

data = WebDriverWait(driver, 20).until(EC.visibility_of_element_located((By.XPATH, "/html/body/div[3]/div[2]/div[5]/div[1]/div/table"))).get_attribute("outerHTML")
df = pd.read_html(data)
df[0]
# So finally we see that by using the dataframe from pandas we read the data from html as it is storing the table data as list data and display as dataframe

    Rank                      State GSDP (Cr INR at Current prices)            \
    Rank                      State                           19-20     18-19
0    1.0                Maharashtra                               -   2632792
1    2.0                 Tamil Nadu                         1845853   1630208
2    3.0              Uttar Pradesh                         1687818   1584764
3    4.0                    Gujarat                               -   1502899
4    5.0                  Karnataka                         1631977   1493127
5    6.0                West Bengal                         1253832   1089898
6    7.0                  Rajasthan                         1020989    942586
7    8.0             Andhra Pradesh                          972782    862957
8    9.0                  Telangana                          969604    861031
9   10.0             Madhya Pradesh                          906672    809592
10  11.0                     Kerala                               -    781653
11  12.0                      Delhi                          856112    774870
12  13.0                    Haryana                          831610    734163
13  14.0                      Bihar                          611804    530363
14  15.0                     Punjab                          574760    526376
15  16.0                     Odisha                          521275    487805
16  17.0                      Assam                               -    315881
17  18.0               Chhattisgarh                          329180    304063
18  19.0                  Jharkhand                          328598    297204
19  20.0                Uttarakhand                               -    245895
20  21.0            Jammu & Kashmir                               -    155956
21  22.0           Himachal Pradesh                          165472    153845
22  23.0                        Goa                           80449     73170
23  24.0                    Tripura                           55984     49845
24  25.0                 Chandigarh                               -     42114
25  26.0                 Puducherry                           38253     34433
26  27.0                  Meghalaya                           36572     33481
27  28.0                     Sikkim                           32496     28723
28  29.0                    Manipur                           31790     27870
29  30.0                   Nagaland                               -     27283
30  31.0          Arunachal Pradesh                               -     24603
31  32.0                    Mizoram                           26503     22287
32  33.0  Andaman & Nicobar Islands                               -         -
33   NaN                      India                        20351013  18886957

     Share GDP ($billion) GSDP (Cr INR at 2011-12 prices)
     18-19           2019                           19-20     18-19
0   13.94%        399.921                               -   2039074
1    8.63%        247.629                         1312929   1215307
2    8.39%        240.726                         1166817   1123982
3    7.96%        228.290                               -   1186379
4    7.91%        226.806                         1156039   1091077
5    5.77%        165.556                          793223    739525
6    4.99%        143.179                          711627    677428
7    4.57%        131.083                          672018    621301
8    4.56%        130.791                          663258    612828
9    4.29%        122.977                          561801    522009
10   4.14%        118.733                               -    559412
11   4.10%        117.703                          634408    590569
12   3.89%        111.519                          572240    531085
13   2.81%         80.562                          414977    375651
14   2.79%         79.957                          418868    397669
15   2.58%         74.098                          396499    376877
16   1.67%         47.982                               -    234048
17   1.61%         46.187                          243477    231182
18   1.57%         45.145                          240036    224986
19   1.30%         37.351                               -    193273
20   0.83%         23.690                               -    112755
21   0.81%         23.369                          124403    117851
22   0.39%         11.115                           63408     57787
23   0.26%          7.571                           40583     36963
24   0.22%          6.397                               -     31192
25   0.18%          5.230                           25093     23013
26   0.18%          5.086                           26695     24682
27   0.15%          4.363                           20017     18722
28   0.15%          4.233                           20673     19300
29   0.14%          4.144                               -     17647
30   0.13%          3.737                               -     16676
31   0.12%          3.385                           18797     16478
32       -              -                               -         -
33     NaN           2869                        14569268  14003316

# Exercise 5:

In [64]:
#Opening up github.com website on automated chrome window

url = 'https://github.com/'
driver.get(url)

In [65]:
#clicking using absolute xpath function to click the Open Source button on homepage and select Trending from the dropdown menu
time.sleep(3)
search_btn =  driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button")
search_btn.click()

search_btn1 =  driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a")
search_btn1.click()

In [78]:
#Lets extract all the elements having Repository Titles

Series = []
title_tags = driver.find_elements(By.XPATH,"//h1[@class='h3 lh-condensed']")
for i in title_tags:
    Series.append(i.text.split('\n'))
print(Series)

[['fuergaosi233 / wechat-chatgpt'], ['acheong08 / ChatGPT'], ['ggerganov / whisper.cpp'], ['openai / whisper'], ['bupticybee / ChineseAiDungeonChatGPT'], ['android / architecture-templates'], ['flutter / flutter'], ['transitive-bullshit / chatgpt-api'], ['rawandahmad698 / PyChatGPT'], ['poteto / hiring-without-whiteboards'], ['airbnb / lottie-ios'], ['cpq / bare-metal-programming-guide'], ['qunash / chatgpt-advanced'], ['wong2 / chat-gpt-google-extension'], ['humanloop / awesome-chatgpt'], ['microsoft / PowerToys'], ['helix-editor / helix'], ['sudoskys / Openaibot'], ['Tencent / Hippy'], ['Netflix / conductor'], ['labteral / chatgpt-python'], ['f / awesome-chatgpt-prompts'], ['microsoft / vscode'], ['gorilla / mux'], ['AutumnWhj / ChatGPT-wechat-bot']]

In [79]:
#Lets extract all the elements having Repository Description

Series = []
title_tags = driver.find_elements(By.XPATH,"//p[@class='col-9 color-fg-muted my-1 pr-4']")
for i in title_tags:
    Series.append(i.text.split('\n'))
print(Series)

[['Use ChatGPT On Wechat via wechaty'], ["Lightweight package for interacting with ChatGPT's API by OpenAI. Uses reverse engineered official API."], ["Port of OpenAI's Whisper model in C/C++"], ['Robust Speech Recognition via Large-Scale Weak Supervision'], ['中文版的ai地牢，直接使用的openai的ChatGPT api作为讲故事的模型。'], ['Flutter makes it easy and fast to build beautiful apps for mobile and beyond'], ['Node.js client for the unofficial ChatGPT API. 🔥'], ['⚡️ Python client for the unofficial ChatGPT API with auto token regeneration, conversation tracking, proxy support and more.'], ["⭐️ Companies that don't have a broken hiring process"], ['An iOS library to natively render After Effects vector animations'], ['A bare metal programming guide on STM32 microcontroller'], ['A browser extension that augments your ChatGPT prompts with web results.'], ['A browser extension to display ChatGPT response alongside Google Search results'], ['Curated list of awesome tools, demos, docs for ChatGPT and GPT-3'], ['Windows system utilities to maximize productivity'], ['A post-modern modal text editor.'], ["🤖 Using OpenAi's Api on Telegram to achieve chatGPT func|在 Telegram 上使用 openai *API* 对话/续写 异步机器人| 👋 支持上下文对话 | 一键部署⚡️ | 非逆向"], ['Hippy is designed to easily build cross-platform dynamic apps. 👏'], ['Conductor is a microservices orchestration engine.'], ["Unofficial Python SDK for OpenAI's ChatGPT"], ['This repo includes ChatGPT promt curation to use ChatGPT better.'], ['Visual Studio Code'], ['A powerful HTTP router and URL matcher for building Go web servers with 🦍'], ['ChatGPT for wechat']]

In [80]:
#Lets extract all the elements having Type of language 

Series = []
title_tags = driver.find_elements(By.XPATH,"//span[@class='d-inline-block ml-0 mr-3']")
for i in title_tags:
    Series.append(i.text.split('\n'))
print(Series)

[['TypeScript'], ['Python'], ['C'], ['Jupyter Notebook'], ['Python'], ['Dart'], ['TypeScript'], ['Python'], ['JavaScript'], ['Swift'], ['C'], ['JavaScript'], ['CSS'], ['C#'], ['Rust'], ['Python'], ['C++'], ['Java'], ['Python'], ['TypeScript'], ['Go'], ['TypeScript']]

In [81]:
#Copying the URl of the repostory as the contributor count is not displayed in the mainpage 

Rep_url = []
url = driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]//a')
for i in url:
    Rep_url.append(i.get_attribute('href')) #to retrieve any link we use get attribute
    time.sleep(0)

In [82]:
Rep_url #Displaying the URLS

['https://github.com/fuergaosi233/wechat-chatgpt',
 'https://github.com/acheong08/ChatGPT',
 'https://github.com/ggerganov/whisper.cpp',
 'https://github.com/openai/whisper',
 'https://github.com/bupticybee/ChineseAiDungeonChatGPT',
 'https://github.com/android/architecture-templates',
 'https://github.com/flutter/flutter',
 'https://github.com/transitive-bullshit/chatgpt-api',
 'https://github.com/rawandahmad698/PyChatGPT',
 'https://github.com/poteto/hiring-without-whiteboards',
 'https://github.com/airbnb/lottie-ios',
 'https://github.com/cpq/bare-metal-programming-guide',
 'https://github.com/qunash/chatgpt-advanced',
 'https://github.com/wong2/chat-gpt-google-extension',
 'https://github.com/humanloop/awesome-chatgpt',
 'https://github.com/microsoft/PowerToys',
 'https://github.com/helix-editor/helix',
 'https://github.com/sudoskys/Openaibot',
 'https://github.com/Tencent/Hippy',
 'https://github.com/Netflix/conductor',
 'https://github.com/labteral/chatgpt-python',
 'https://github.com/f/awesome-chatgpt-prompts',
 'https://github.com/microsoft/vscode',
 'https://github.com/gorilla/mux',
 'https://github.com/AutumnWhj/ChatGPT-wechat-bot']

In [85]:
#To extract the contributors count from each url

Contr_count  = []


for i in Rep_url:
    driver.get(i)
    time.sleep(0)
    try:
        description=driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/main/turbo-frame/div/div/div/div[3]/div[2]/div/div[4]/div/h2/a/span')
        Contr_count.append(description.text.split('\n'))
    except NoSuchElementException :
        Contr_count.append('-')

In [86]:
Contr_count

[['11'],
 ['49'],
 ['25'],
 ['31'],
 ['3'],
 ['3'],
 '-',
 [''],
 '-',
 ['1,005'],
 ['184'],
 ['2'],
 '-',
 '-',
 ['3'],
 ['323'],
 ['410'],
 ['2'],
 ['11'],
 ['49'],
 ['2'],
 ['7'],
 ['1,760'],
 ['91.4k'],
 '-']

# Exercise 6:

In [87]:
#Opening up billborad.com website on automated chrome window

url = 'https:/www.billboard.com/'
driver.get(url)

In [89]:
#clicking using absolute xpath function to click the Side menu button on homepage and select Charts from the dropdown menu
time.sleep(3)
search_btn =  driver.find_element(By.XPATH,"/html/body/div[3]/header/div/div[4]/div/div[1]/div[1]/button")
search_btn.click()

In [90]:
search_btn1 =  driver.find_element(By.XPATH,"/html/body/div[3]/div[8]/div/div/div/ul/li[1]/h3/a")
search_btn1.click()

In [91]:
search_btn1 =  driver.find_element(By.XPATH,"/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a")
search_btn1.click()

In [104]:
#Lets extract all the elements having Type of language 

Series = []
title_tags = driver.find_elements(By.XPATH,"//div[@class='o-chart-results-list-row-container']")
for i in title_tags:
    Series.append(i.text.split('\n'))
print(Series)

[['1', 'Anti-Hero', 'Taylor Swift', '1', '1', '6'], ['2', 'All I Want For Christmas Is You', 'Mariah Carey', '5', '1', '54'], ['3', "Rockin' Around The Christmas Tree", 'Brenda Lee', '6', '2', '48'], ['4', 'Unholy', 'Sam Smith & Kim Petras', '3', '1', '10'], ['5', 'Jingle Bell Rock', 'Bobby Helms', '9', '3', '45'], ['6', 'A Holly Jolly Christmas', 'Burl Ives', '10', '4', '28'], ['7', 'Rich Flex', 'Drake & 21 Savage', '2', '2', '4'], ['8', 'Bad Habit', 'Steve Lacy', '4', '1', '22'], ['9', "It's The Most Wonderful Time Of The Year", 'Andy Williams', '19', '5', '29'], ['10', 'Last Christmas', 'Wham!', '23', '7', '27'], ['11', "I'm Good (Blue)", 'David Guetta & Bebe Rexha', '7', '7', '14'], ['12', 'The Christmas Song (Merry Christmas To You)', 'Nat King Cole', '34', '11', '34'], ['13', 'Feliz Navidad', 'Jose Feliciano', '42', '6', '22'], ['14', 'As It Was', 'Harry Styles', '8', '1', '35'], ['15', 'Die For You', 'The Weeknd', '12', '12', '18'], ['16', 'Sleigh Ride', 'The Ronettes', '40', '10', '18'], ['17', 'Underneath The Tree', 'Kelly Clarkson', '48', '12', '17'], ['18', 'Let It Snow, Let It Snow, Let It Snow', 'Dean Martin', '41', '8', '21'], ['19', "It's Beginning To Look A Lot Like Christmas", 'Perry Como And The Fontane Sisters With Mitchell Ayres And His Orchestra', '43', '12', '14'], ['20', 'Cuff It', 'Beyonce', '16', '13', '16'], ['21', 'Under The Influence', 'Chris Brown', '14', '14', '12'], ['22', 'Lift Me Up', 'Rihanna', '11', '2', '5'], ['23', 'RE- ENTRY', 'Christmas (Baby Please Come Home)', 'Darlene Love', '-', '16', '13'], ['24', 'RE- ENTRY', 'Santa Tell Me', 'Ariana Grande', '-', '17', '14'], ['25', 'You Proof', 'Morgan Wallen', '13', '5', '29'], ['26', 'Super Freaky Girl', 'Nicki Minaj', '15', '1', '16'], ['27', 'I Like You (A Happier Song)', 'Post Malone Featuring Doja Cat', '18', '3', '26'], ['28', 'Something In The Orange', 'Zach Bryan', '17', '12', '32'], ['29', 'RE- ENTRY', "It's Beginning To Look A Lot Like Christmas", 'Michael Buble', '-', '20', '11'], ['30', 'RE- ENTRY', 'Deck The Halls', 'Nat King Cole', '-', '30', '4'], ['31', 'RE- ENTRY', 'White Christmas', 'Bing Crosby', '-', '12', '26'], ['32', 'Wasted On You', 'Morgan Wallen', '20', '9', '55'], ['33', 'RE- ENTRY', 'Jingle Bells', 'Frank Sinatra', '-', '33', '5'], ['34', 'RE- ENTRY', 'Rudolph The Red-Nosed Reindeer', 'Gene Autry', '-', '16', '18'], ['35', 'Just Wanna Rock', 'Lil Uzi Vert', '21', '21', '7'], ['36', 'Made You Look', 'Meghan Trainor', '24', '24', '6'], ['37', 'Tomorrow 2', 'GloRilla & Cardi B', '22', '9', '10'], ['38', 'Vegas', 'Doja Cat', '25', '10', '26'], ['39', 'RE- ENTRY', 'Here Comes Santa Claus (Right Down Santa Claus Lane)', 'Gene Autry', '-', '26', '11'], ['40', 'Wait For U', 'Future Featuring Drake & Tems', '29', '1', '31'], ['41', 'Golden Hour', 'JVKE', '35', '35', '14'], ['42', 'RE- ENTRY', "You're A Mean One, Mr. Grinch", 'Thurl Ravenscroft', '-', '32', '5'], ['43', 'RE- ENTRY', 'Blue Christmas', 'Elvis Presley', '-', '33', '4'], ['44', 'Titi Me Pregunto', 'Bad Bunny', '28', '5', '30'], ['45', "I Ain't Worried", 'OneRepublic', '27', '6', '25'], ['46', 'Jimmy Cooks', 'Drake Featuring 21 Savage', '36', '1', '24'], ['47', 'Sunroof', 'Nicky Youre & dazy', '33', '4', '27'], ['48', 'About Damn Time', 'Lizzo', '44', '1', '33'], ['49', 'RE- ENTRY', "Santa Claus Is Comin' To Town", 'Jackson 5', '-', '41', '3'], ['50', 'She Had Me At Heads Carolina', 'Cole Swindell', '38', '16', '27'], ['51', 'Fall In Love', 'Bailey Zimmerman', '49', '29', '31'], ['52', 'Lavender Haze', 'Taylor Swift', '26', '2', '6'], ['53', 'Spin Bout U', 'Drake & 21 Savage', '31', '5', '4'], ['54', 'Until I Found You', 'Stephen Sanchez', '45', '38', '22'], ['55', 'Thank God', 'Kane Brown With Katelyn Brown', '46', '22', '12'], ['56', 'Circo Loco', 'Drake & 21 Savage', '37', '8', '4'], ['57', "Victoria's Secret", 'Jax', '59', '35', '18'], ['58', 'On BS', 'Drake & 21 Savage', '39', '4', '4'], ['59', 'Major Distribution', 'Drake & 21 Savage', '30', '3', '4'], ['60', 'Son Of A Sinner', 'Jelly Roll', '61', '31', '22'], ['61', 'Rock And A Hard Place', 'Bailey Zimmerman', '54', '24', '25'], ['62', 'What My World Spins Around', 'Jordan Davis', '55', '41', '16'], ['63', "Star Walkin' (League Of Legends Worlds Anthem)", 'Lil Nas X', '64', '32', '10'], ['64', 'Pussy & Millions', 'Drake & 21 Savage Featuring Travis Scott', '47', '6', '4'], ['65', 'Wait In The Truck', 'HARDY Featuring Lainey Wilson', '53', '51', '13'], ['66', 'Shirt', 'SZA', '63', '11', '5'], ['67', 'Hold Me Closer', 'Elton John & Britney Spears', '51', '6', '14'], ['68', 'Half Of Me', 'Thomas Rhett Featuring Riley Green', '56', '52', '15'], ['69', "Don't Come Lookin'", 'Jackson Dean', '60', '50', '14'], ['70', 'Bejeweled', 'Taylor Swift', '50', '6', '6'], ['71', 'Midnight Rain', 'Taylor Swift', '52', '5', '6'], ['72', 'Romantic Homicide', 'd4vd', '72', '33', '13'], ['73', 'Maroon', 'Taylor Swift', '58', '3', '6'], ['74', 'Free Mind', 'Tems', '74', '46', '20'], ['75', 'Privileged Rappers', 'Drake & 21 Savage', '62', '7', '4'], ['76', 'Whiskey On You', 'Nate Smith', '71', '44', '24'], ['77', 'Billie Eilish.', 'Armani White', '75', '58', '12'], ['78', 'Karma', 'Taylor Swift', '65', '9', '6'], ['79', 'Broke Boys', 'Drake & 21 Savage', '68', '12', '4'], ['80', "You're On Your Own, Kid", 'Taylor Swift', '67', '8', '6'], ['81', 'BackOutsideBoyz', 'Drake', '66', '9', '4'], ['82', 'Heyy', 'Lil Baby', '80', '21', '8'], ['83', 'Snow On The Beach', 'Taylor Swift Featuring Lana Del Rey', '69', '4', '6'], ['84', 'No Se Va', 'Grupo Frontera', '79', '57', '10'], ['85', 'All Mine', 'Brent Faiyaz', '93', '42', '17'], ['86', 'California Breeze', 'Lil Baby', '81', '4', '7'], ['87', 'Calm Down', 'Rema & Selena Gomez', '82', '74', '13'], ['88', 'Hours In Silence', 'Drake & 21 Savage', '70', '11', '4'], ['89', 'Country On', 'Luke Bryan', '83', '72', '15'], ['90', 'Freestyle', 'Lil Baby', '90', '63', '12'], ['91', 'NEW', 'Last Christmas', 'Lauren Spencer-Smith', '-', '91', '1'], ['92', 'Jumbotron Shit Poppin', 'Drake', '77', '16', '4'], ['93', 'Pick Me Up', 'Gabby Barrett', '87', '69', '18'], ['94', 'Heart Like A Truck', 'Lainey Wilson', '86', '86', '3'], ['95', 'La Bachata', 'Manuel Turizo', '94', '67', '15'], ['96', 'NEW', 'Someday At Christmas', 'Lizzo', '-', '96', '1'], ['97', 'Vigilante Shit', 'Taylor Swift', '73', '10', '6'], ['98', 'RE- ENTRY', 'Forget Me', 'Lewis Capaldi', '-', '95', '6'], ['99', 'Going, Going, Gone', 'Luke Combs', '98', '98', '3'], ['100', 'Miss You', 'Oliver Tree & Robin Schulz', '91', '84', '6']]

# Exercise 7 :

In [3]:
#Opening up naukri.com website on automated chrome window

url = 'https://www.naukri.com/'
driver.get(url)

In [4]:
#Clicking on the sitemap option at the bottom of page as the new website does not have recruiters 
search_btn1 =  driver.find_element(By.XPATH,"/html/body/div[1]/footer/section[1]/div/div/div[2]/ul/li[4]/a")
search_btn1.click()

In [5]:
#clicking using absolute xpath function to click the Recruiters button on homepage and select Browse all recruiters from the dropdown menu
time.sleep(3)
search_btn =  driver.find_element(By.XPATH,"/html/body/div[1]/div/ul/li[2]/a")
search_btn.click()

search_btn1 =  driver.find_element(By.XPATH,"/html/body/div[1]/div/ul/li[2]/div/ul/li[1]/a")
search_btn1.click()

In [234]:
#finding the web element for the Search bar and enter Data Science

search_prod = driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[2]/div/form/div[1]/div/div[1]/div[1]/div[2]/input") 
search_prod.send_keys('Data Science')

In [237]:
#clicking using absolute xpath function to click the search button

search_btn =  driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[2]/div/form/div[1]/button")
search_btn.click()

In [19]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC # expected_conditions module contains a set of predefined conditions to use with WebDriverWait used for the visibility_of_element_located to be able to get the elements in the table as shown on website list  
import pandas as pd
import html5lib
import lxml
from bs4 import BeautifulSoup

In [20]:
#To scrap data from multiple pages with the recruiters details , found 6120 posts and all are scrapped 

name =[]
designation=[]
company = []
skills = []
location = []

start = 0

end = 120

for page in range(start,end):
    try:
        a1 = driver.find_elements(By.XPATH,"//span[@class='fl ellipsis']")
        a2 = driver.find_elements(By.XPATH,'//span[@class="ellipsis clr"]')
        a3 = driver.find_elements(By.XPATH,'//li[@class="cmpIcn"]')
        a4 = driver.find_elements(By.XPATH,'//div[@class="hireSec highlightable"]')
        a5 = driver.find_elements(By.XPATH,'//li[@class="locIcn"]')
        wait_button = WebDriverWait(driver, 10)
        for i in a1:
            name.append(i.text)
        for i in a2:
            designation.append(i.text)
        for i in a3:
            company.append(i.text)
        for i in a4:
            skills.append(i.text)        
        for i in a5:
            location.append(i.text)
        next_button = driver.find_element(By.XPATH,'//button[@class="pagination"]') #to scrap data from the next page 
        next_button.click()
        time.sleep(3)
    except NoSuchElementException :  
            name.append('-')
            designation.append('-')
            company.append('-')
            skills.append('-')
            location.append('-')

In [25]:
print (len(name),len(designation),len(company),len(skills),len(location))

6120 6120 120 6120 120

# Exercise 8:

In [27]:
#Opening up theguardian.com website on automated chrome window

url = 'https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(url)

In [28]:
#Scraping the table fully from the webpage
data = WebDriverWait(driver, 20).until(EC.visibility_of_element_located((By.XPATH, '//*[@id="article-body-blocks"]/div/table'))).get_attribute("outerHTML")
df = pd.read_html(data)
df[0]
# So finally we see that by using the dataframe from pandas we read the data from html as it is storing the table data as list data and display as dataframe

,Rank,Title,Author,Volume Sales,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan",5094805,Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.",4475152,Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.",4200654,Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.",4179479,Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.",3758936,Random House,Romance & Sagas
...,...,...,...,...,...,...
96,97,Happy Days with the Naked Chef,"Oliver, Jamie",794201,Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne",792187,Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave",791507,Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie",791095,Penguin,Food & Drink: General
100,SOURCE: NIELSEN BOOK SCAN,SOURCE: NIELSEN BOOK SCAN,SOURCE: NIELSEN BOOK SCAN,SOURCE: NIELSEN BOOK SCAN,SOURCE: NIELSEN BOOK SCAN,SOURCE: NIELSEN BOOK SCAN

# Exercise 9:

In [36]:
#Opening up naukri.com website on automated chrome window

url = 'https://www.imdb.com/list/ls095964455/'
driver.get(url)

In [48]:
#To scrap data the top 100 series from page and get the info in each list typt

name =[]
Year_Span=[]
Genre = []
Run_Time = []
Ratings = []
Votes = []

start = 0

end = 1

for page in range(start,end):
    try:
        a1 = driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']//a")
        a2 = driver.find_elements(By.XPATH,'//span[@class="lister-item-year text-muted unbold"]')
        a3 = driver.find_elements(By.XPATH,'//span[@class="genre"]')
        a4 = driver.find_elements(By.XPATH,'//span[@class="runtime"]')
        a5 = driver.find_elements(By.XPATH,'//span[@class="ipl-rating-star__rating"]')
        a6 = driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]//span')
        #wait_button = WebDriverWait(driver, 10)
        for i in a1:
            name.append(i.text.split('\n'))
        for i in a2:
            Year_Span.append(i.text)
        for i in a3:
            Genre.append(i.text)
        for i in a4:
            Run_Time.append(i.text)        
        for i in a5:
            Ratings.append(i.text)
        for i in a6:
            Votes.append(i.text.split('\n'))  
        #next_button = driver.find_element(By.XPATH,'//button[@class="pagination"]') #to scrap data from the next page 
        #next_button.click()
        #time.sleep(3)
    except NoSuchElementException :  
            name.append('-')
            Year_Span.append('-')
            Genre.append('-')
            Run_Time.append('-')
            Ratings.append('-')
            Votes.append('-')

In [49]:
name

[['Game of Thrones'],
 ['Stranger Things'],
 ['The Walking Dead'],
 ['13 Reasons Why'],
 ['The 100'],
 ['Orange Is the New Black'],
 ['Riverdale'],
 ["Grey's Anatomy"],
 ['The Flash'],
 ['Arrow'],
 ['Money Heist'],
 ['The Big Bang Theory'],
 ['Black Mirror'],
 ['Sherlock'],
 ['Vikings'],
 ['Pretty Little Liars'],
 ['The Vampire Diaries'],
 ['American Horror Story'],
 ['Breaking Bad'],
 ['Lucifer'],
 ['Supernatural'],
 ['Prison Break'],
 ['How to Get Away with Murder'],
 ['Teen Wolf'],
 ['The Simpsons'],
 ['Once Upon a Time'],
 ['Narcos'],
 ['Daredevil'],
 ['Friends'],
 ['How I Met Your Mother'],
 ['Suits'],
 ['Mr. Robot'],
 ['The Originals'],
 ['Supergirl'],
 ['Gossip Girl'],
 ['Sense8'],
 ['Gotham'],
 ['Westworld'],
 ['Jessica Jones'],
 ['Modern Family'],
 ['Rick and Morty'],
 ['Shadowhunters'],
 ['The End of the F***ing World'],
 ['House of Cards'],
 ['Dark'],
 ['Elite'],
 ['Sex Education'],
 ['Shameless'],
 ['New Girl'],
 ['Agents of S.H.I.E.L.D.'],
 ['You'],
 ['Dexter'],
 ['Fear the Walking Dead'],
 ['Family Guy'],
 ['The Blacklist'],
 ['Lost'],
 ['Peaky Blinders'],
 ['House'],
 ['Quantico'],
 ['Orphan Black'],
 ['Homeland'],
 ['Blindspot'],
 ["DC's Legends of Tomorrow"],
 ["The Handmaid's Tale"],
 ['Chilling Adventures of Sabrina'],
 ['The Good Doctor'],
 ['Jane the Virgin'],
 ['Glee'],
 ['South Park'],
 ['Brooklyn Nine-Nine'],
 ['Under the Dome'],
 ['The Umbrella Academy'],
 ['True Detective'],
 ['The OA'],
 ['Desperate Housewives'],
 ['Better Call Saul'],
 ['Bates Motel'],
 ['The Punisher'],
 ['Atypical'],
 ['Dynasty'],
 ['This Is Us'],
 ['The Good Place'],
 ['Iron Fist'],
 ['The Rain'],
 ['Mindhunter'],
 ['Revenge'],
 ['Luke Cage'],
 ['Scandal'],
 ['The Defenders'],
 ['Big Little Lies'],
 ['Insatiable'],
 ['The Mentalist'],
 ['The Crown'],
 ['Chernobyl'],
 ['iZombie'],
 ['Reign'],
 ['A Series of Unfortunate Events'],
 ['Criminal Minds'],
 ['Scream: The TV Series'],
 ['The Haunting of Hill House']]

In [50]:
Year_Span

['(2011–2019)',
 '(2016– )',
 '(2010–2022)',
 '(2017–2020)',
 '(2014–2020)',
 '(2013–2019)',
 '(2017– )',
 '(2005– )',
 '(2014–2023)',
 '(2012–2020)',
 '(2017–2021)',
 '(2007–2019)',
 '(2011–2019)',
 '(2010–2017)',
 '(2013–2020)',
 '(2010–2017)',
 '(2009–2017)',
 '(2011– )',
 '(2008–2013)',
 '(2016–2021)',
 '(2005–2020)',
 '(2005–2017)',
 '(2014–2020)',
 '(2011–2017)',
 '(1989– )',
 '(2011–2018)',
 '(2015–2017)',
 '(2015–2018)',
 '(1994–2004)',
 '(2005–2014)',
 '(2011–2019)',
 '(2015–2019)',
 '(2013–2018)',
 '(2015–2021)',
 '(2007–2012)',
 '(2015–2018)',
 '(2014–2019)',
 '(2016–2022)',
 '(2015–2019)',
 '(2009–2020)',
 '(2013– )',
 '(2016–2019)',
 '(2017–2019)',
 '(2013–2018)',
 '(2017–2020)',
 '(2018– )',
 '(2019– )',
 '(2011–2021)',
 '(2011–2018)',
 '(2013–2020)',
 '(2018– )',
 '(2006–2013)',
 '(2015– )',
 '(1999– )',
 '(2013– )',
 '(2004–2010)',
 '(2013–2022)',
 '(2004–2012)',
 '(2015–2018)',
 '(2013–2017)',
 '(2011–2020)',
 '(2015–2020)',
 '(2016–2022)',
 '(2017– )',
 '(2018–2020)',
 '(2017– )',
 '(2014–2019)',
 '(2009–2015)',
 '(1997– )',
 '(2013–2021)',
 '(2013–2015)',
 '(2019–2023)',
 '(2014–2019)',
 '(2016–2019)',
 '(2004–2012)',
 '(2015–2022)',
 '(2013–2017)',
 '(2017–2019)',
 '(2017–2021)',
 '(2017–2022)',
 '(2016–2022)',
 '(2016–2020)',
 '(2017–2018)',
 '(2018–2020)',
 '(2017–2019)',
 '(2011–2015)',
 '(2016–2018)',
 '(2012–2018)',
 '(2017)',
 '(2017–2019)',
 '(2018–2019)',
 '(2008–2015)',
 '(2016– )',
 '(2019)',
 '(2015–2019)',
 '(2013–2017)',
 '(2017–2019)',
 '(2005– )',
 '(2015–2019)',
 '(2018)']

In [51]:
Genre

['Action, Adventure, Drama',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Thriller',
 'Drama, Mystery, Thriller',
 'Drama, Mystery, Sci-Fi',
 'Comedy, Crime, Drama',
 'Crime, Drama, Mystery',
 'Drama, Romance',
 'Action, Adventure, Drama',
 'Action, Adventure, Crime',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Drama, Mystery, Sci-Fi',
 'Crime, Drama, Mystery',
 'Action, Adventure, Drama',
 'Drama, Mystery, Romance',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Sci-Fi',
 'Crime, Drama, Thriller',
 'Crime, Drama, Fantasy',
 'Drama, Fantasy, Horror',
 'Action, Crime, Drama',
 'Crime, Drama, Mystery',
 'Action, Drama, Fantasy',
 'Animation, Comedy',
 'Adventure, Fantasy, Romance',
 'Biography, Crime, Drama',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Comedy, Romance',
 'Comedy, Drama',
 'Crime, Drama, Thriller',
 'Drama, Fantasy, Horror',
 'Action, Adventure, Drama',
 'Drama, Romance',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Comedy, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Action, Drama, Fantasy',
 'Adventure, Comedy, Crime',
 'Drama',
 'Crime, Drama, Mystery',
 'Crime, Drama, Thriller',
 'Comedy, Drama',
 'Comedy, Drama',
 'Comedy, Romance',
 'Action, Adventure, Drama',
 'Crime, Drama, Romance',
 'Crime, Drama, Mystery',
 'Drama, Horror, Sci-Fi',
 'Animation, Comedy',
 'Crime, Drama, Mystery',
 'Adventure, Drama, Fantasy',
 'Crime, Drama',
 'Drama, Mystery',
 'Crime, Drama, Mystery',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Action, Crime, Drama',
 'Action, Adventure, Drama',
 'Drama, Sci-Fi, Thriller',
 'Drama, Fantasy, Horror',
 'Drama',
 'Comedy',
 'Comedy, Drama, Music',
 'Animation, Comedy',
 'Comedy, Crime',
 'Drama, Mystery, Sci-Fi',
 'Action, Adventure, Comedy',
 'Crime, Drama, Mystery',
 'Drama, Fantasy, Mystery',
 'Comedy, Drama, Mystery',
 'Crime, Drama',
 'Drama, Horror, Mystery',
 'Action, Crime, Drama',
 'Comedy, Drama',
 'Drama',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Fantasy',
 'Action, Adventure, Crime',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Drama, Mystery, Thriller',
 'Action, Crime, Drama',
 'Drama, Thriller',
 'Action, Adventure, Crime',
 'Crime, Drama, Mystery',
 'Comedy, Drama, Thriller',
 'Crime, Drama, Mystery',
 'Biography, Drama, History',
 'Drama, History, Thriller',
 'Comedy, Crime, Drama',
 'Drama',
 'Adventure, Comedy, Drama',
 'Crime, Drama, Mystery',
 'Comedy, Crime, Drama',
 'Drama, Horror, Mystery']

In [52]:
Run_Time

['57 min',
 '51 min',
 '44 min',
 '60 min',
 '43 min',
 '59 min',
 '45 min',
 '41 min',
 '43 min',
 '42 min',
 '70 min',
 '22 min',
 '60 min',
 '88 min',
 '44 min',
 '44 min',
 '43 min',
 '60 min',
 '49 min',
 '42 min',
 '44 min',
 '44 min',
 '43 min',
 '41 min',
 '22 min',
 '60 min',
 '49 min',
 '54 min',
 '22 min',
 '22 min',
 '44 min',
 '49 min',
 '45 min',
 '43 min',
 '42 min',
 '60 min',
 '42 min',
 '62 min',
 '56 min',
 '22 min',
 '23 min',
 '42 min',
 '25 min',
 '51 min',
 '60 min',
 '60 min',
 '45 min',
 '46 min',
 '22 min',
 '45 min',
 '45 min',
 '53 min',
 '44 min',
 '22 min',
 '43 min',
 '44 min',
 '60 min',
 '44 min',
 '42 min',
 '44 min',
 '55 min',
 '42 min',
 '42 min',
 '60 min',
 '60 min',
 '41 min',
 '60 min',
 '44 min',
 '22 min',
 '22 min',
 '43 min',
 '60 min',
 '55 min',
 '60 min',
 '45 min',
 '46 min',
 '45 min',
 '53 min',
 '30 min',
 '42 min',
 '45 min',
 '22 min',
 '55 min',
 '45 min',
 '60 min',
 '44 min',
 '55 min',
 '43 min',
 '50 min',
 '60 min',
 '45 min',
 '43 min',
 '58 min',
 '330 min',
 '42 min',
 '42 min',
 '50 min',
 '42 min',
 '45 min',
 '572 min']

In [120]:
Ratings

['9.2',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.7',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.1',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '7.5',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '7.6',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.1',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '6.6',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '7.6',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '7.6',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '7.5',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.2',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.2',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.8',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '9.1',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.5',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '7.4',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '7.7',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '9.5',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.1',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.4',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.3',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.1',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '7.7',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.7',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '7.7',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.8',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.6',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.9',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.3',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.5',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.6',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.3',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '6.2',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '7.5',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.2',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '7.8',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.5',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '7.9',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.5',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '9.1',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '6.5',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.1',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8.7',
 '',
 'Rate',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 ...]

In [60]:
Votes[::-7]

[['245,375'],
 ['41,586'],
 ['198,473'],
 ['61,504'],
 ['50,204'],
 ['68,722'],
 ['749,021'],
 ['217,088'],
 ['185,790'],
 ['29,132'],
 ['199,677'],
 ['108,524'],
 ['74,357'],
 ['131,867'],
 ['120,503'],
 ['288,866'],
 ['37,615'],
 ['131,776'],
 ['160,792'],
 ['144,473'],
 ['22,890'],
 ['89,501'],
 ['236,659'],
 ['108,758'],
 ['525,852'],
 ['129,647'],
 ['105,487'],
 ['570,616'],
 ['248,379'],
 ['107,052'],
 ['316,327'],
 ['369,697'],
 ['149,023'],
 ['51,177'],
 ['95,598'],
 ['95,848'],
 ['237,265'],
 ['105,261'],
 ['74,419'],
 ['342,107'],
 ['111,556'],
 ['61,276'],
 ['465,039'],
 ['546,797'],
 ['553,618'],
 ['249,853'],
 ['340,095'],
 ['130,473'],
 ['725,562'],
 ['240,655'],
 ['217,690'],
 ['225,146'],
 ['243,480'],
 ['280,761'],
 ['79,736'],
 ['385,628'],
 ['504,735'],
 ['191,002'],
 ['64,136'],
 ['519,971'],
 ['430,807'],
 ['215,228'],
 ['505,123'],
 ['230,977'],
 ['155,035'],
 ['175,515'],
 ['124,448'],
 ['136,656'],
 ['387,834'],
 ['410,983'],
 ['683,346'],
 ['993,210'],
 ['440,949'],
 ['422,131'],
 ['225,503'],
 ['407,578'],
 ['148,999'],
 ['152,319'],
 ['535,502'],
 ['445,849'],
 ['324,580'],
 ['1,873,774'],
 ['319,789'],
 ['322,377'],
 ['168,075'],
 ['531,914'],
 ['924,610'],
 ['545,948'],
 ['807,437'],
 ['476,240'],
 ['432,046'],
 ['346,396'],
 ['309,039'],
 ['145,546'],
 ['303,012'],
 ['252,118'],
 ['292,957'],
 ['989,445'],
 ['1,180,448'],
 ['2,090,942']]

# Exercise 10:

In [66]:
#Opening up ics.com website on automated chrome window

url = 'https://archive.ics.uci.edu/'
driver.get(url)

In [67]:
#clicking using absolute xpath function to click the ALL DATASET button

search_btn =  driver.find_element(By.XPATH,"/html/body/table[1]/tbody/tr/td[2]/span[2]/a")
search_btn.click()

In [116]:
data = WebDriverWait(driver, 20).until(EC.visibility_of_element_located((By.XPATH, "/html/body/table[2]/tbody/tr/td[2]/table[2]"))).get_attribute("outerHTML")
df = pd.read_html(data)
df[0]
# So finally we see that by using the dataframe from pandas we read the data from html as it is storing the table data as list data and display as dataframe

,0,1,2,3,4,5,6
0,Name,Data Types,Default Task,Attribute Types,# Instances,# Attributes,Year
1,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,NaN,Abalone,NaN,NaN,NaN,NaN,NaN
3,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
4,NaN,Adult,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
1240,NaN,Maternal Health Risk Data Set,NaN,NaN,NaN,NaN,NaN
1241,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
1242,NaN,Room Occupancy Estimation,NaN,NaN,NaN,NaN,NaN
1243,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021
1244,NaN,Image Recognition Task Execution Times in Mobi...,NaN,NaN,NaN,NaN,NaN

In [118]:
df[0][101:110]

,0,1,2,3,4,5,6
101,Ionosphere,Multivariate,Classification,"Integer, Real",351,34,1989
102,NaN,Ionosphere,NaN,NaN,NaN,NaN,NaN
103,Iris,Multivariate,Classification,Real,150,4,1988
104,NaN,Iris,NaN,NaN,NaN,NaN,NaN
105,ISOLET,Multivariate,Classification,Real,7797,617,1994
106,NaN,ISOLET,NaN,NaN,NaN,NaN,NaN
107,Kinship,Relational,Relational-Learning,Categorical,104,12,1990
108,NaN,Kinship,NaN,NaN,NaN,NaN,NaN
109,Labor Relations,Multivariate,NaN,"Categorical, Integer, Real",57,16,1988

In [121]:
driver.close()